### ISSUE TITLE
NPM publish 2.6.0

### ISSUE THREAD

**Issue by junderw** [bitcoinjs/bip39#101]
I have merged a new interface for async usage of pbkdf2. This has increased performance greatly for some users.

@weilu @dcousens

**Comment by junderw** [comment]
Also, since @dcousens has stepped down and left me with the reigns (or at least some of the reigns, on most projects in the org) I was wondering if either of you two could add me on the npm package? @weilu

**Comment by mesqueeb** [comment]
+1 for updating NPM to the main branch! 💯💯💯💯💯

**Comment by PaulBernier** [comment]
Very interested in the async functions too, looking forward for 2.6.0 to get out!

**Comment by junderw** [comment]
I got publish rights!

I'll push it out later today

**Comment by junderw** [comment]
Pushed to npm as 2.6.0
