### ISSUE TITLE
String.prototype.normalize support

### ISSUE THREAD

**Issue by zyuhel** [bitcoinjs/bip39#106]
Doesn't String.prototype.normalize is supported now by most of the browsers? 
May be unorm dependency should be removed and polyfills should be set by builders script of projects using this library?

**Comment by junderw** [comment]
Do you have any data on browser support?

**Comment by xzjcool** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize  seems only android webview not support. the unorm package is too big

**Comment by junderw** [comment]
ok, we'll remove it with the typescript major version change coming up

**Comment by junderw** [comment]
What do you mean non-typescript version?

Typescript is a superset of NodeJS, so if you don't want to use Typescript, just don't pull it into your app.

This is a breaking change, so a major version bump is required.

Next major version will use typescript also.

**Comment by zyuhel** [comment]
So if i understand correctly new major version will be rewritten in typescript?

**Comment by junderw** [comment]
#104 has more info. This will be a version bump.

I have removed unorm from it: https://github.com/bitcoinjs/bip39/pull/104/commits/91b0efd9fb9dbf8668708ec8e6aef96d31936c37
