### ISSUE TITLE
Why not HMAC-SHA512 but SHA512

### ISSUE THREAD

**Issue by Doresimon** [bitcoinjs/bip39#110]
I found in [BIP39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki), they suggested to use HMAC-SHA512 as the pseudo-random function, but in this repo SHA512 is being used. 

Did I got the right doc for mnemonic generation?

Thanks!

**Comment by junderw** [comment]
we use HMAC-SHA512 and all the test vectors pass.

please read the source code more carefully.

Thanks.
