### ISSUE TITLE
import doesn't work anymore in version ^3.0

### ISSUE THREAD

**Issue by lebed2045** [bitcoinjs/bip39#114]
Before I was using version 2.5, and could do something like that (in react.js app)
```
import Bip39 from 'bip39';
...
    if (!Bip39.validateMnemonic(bip39SeedPhrase)) {
            throw new Error("Not valid seed phrase. Expected string with Bip39 12-24 words mnemonic phrase");
        }

        this.seed = Bip39.mnemonicToSeed(bip39SeedPhrase, password);
```
upfotunately it used very heavy dependency unorm.js so I upgraded to version 3.0.

After the upgrade, this code above stop working. So way around was this:
```
import {validateMnemonic, mnemonicToSeedSync,generateMnemonic} from 'bip39';
const Bip39 = {validateMnemonic, mnemonicToSeedSync,generateMnemonic};
```
Is it possible to export the default module as you did before? If you want, I can do pull request.

Also, I couldn't find @types/bip39 anymore. Could you please add  [@types](https://www.npmjs.com/package/@types/bip39) for version 3.0?

**Comment by junderw** [comment]
```typescript
import * as Bip39 from 'bip39';
```

bip39 supports Typescript out of the box. @types are no longer needed.
