### ISSUE TITLE
Secure random number generation is not supported by this browser

### ISSUE THREAD

**Issue by zhangxiaoshang** [bitcoinjs/bip39#117]
I want to generate mnemonic in react-native. I use bip39 with browserify, and getting the error:

```
Error: Secure random number generation is not supported by this browser.
Use Chrome, Firefox or Internet Explorer 11
```

OS: MacOS
node: v9.10.0
npm: 5.6.0
react-native-cli: 2.0.1
react-native: 0.57.1
"expo": "^32.0.0"
"bip39": "^3.0.2"

Here is [the project](https://github.com/zhangxiaoshang/my-wallet/tree/feature/generateMnemonic)

![image](https://user-images.githubusercontent.com/19658966/57347762-0c741000-7186-11e9-87a7-a461e8523244.png)
![image](https://user-images.githubusercontent.com/19658966/57347899-a0de7280-7186-11e9-9288-59c3324a7f9f.png)
![image](https://user-images.githubusercontent.com/19658966/57347944-cf5c4d80-7186-11e9-9b02-a7ca7859bf85.png)

**Comment by junderw** [comment]
react has a separate csprng package.

use it to generate 16 bytes of randomness and pass it to bip39.entropyToMnemonic it will give you 12 word phrase

32 bytes if you want 24 words.

**Comment by junderw** [comment]
I think it is called rn-randombytes but I'm not sure

**Comment by junderw** [comment]
```js
import { randomBytes } from 'react-native-randombytes';

const getRandom = count => new Promise((resolve, reject) => {
  return randomBytes(count, (err, bytes) => {
    if (err) reject(err)
    else resolve(bytes)
  })
})
```

then you can use

```js
async function someFunc() {
  const entropy = await getRandom(16)
  console.log(bip39.entropyToMnemonic(entropy))
```

**Comment by zhangxiaoshang** [comment]
@junderw 
not work and get another error:
`
The package at "node_modules/sjcl/sjcl.js" attempted to import the Node standard library module "crypto". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq/#can-i-use-nodejs-packages-with-expo
`

**Comment by junderw** [comment]
you did not do what I said.

**Comment by junderw** [comment]
Please do your own dev work.

This library is only guaranteed to work in the browser and NodeJS environments.

Anything else will require you to figure out how to make it work, trial and error.

Do what I said and it will work.

Synchronus calls use SJCL which relies on crypto, which react cannot use. Asynchronus calls use the native iOS/Android calls.

**Comment by JiangYongKang** [comment]
@zhangxiaoshang 
Try to define your random bytes function, example:
```js
const bip39 = require('bip39')
let randomBytes = randomBytes() {
    let bytes = new Int8Array(32)
    // random random random
    return bytes
}
let mneminic = bip39.generateMnemonic(32, randomBytes)
console.log(mneminic)
// praise seek audit undo salmon borrow flag fox stock window coil hotel memory frequent business winner liquid valid diary plug laundry version offer fun
```

**Comment by leoparis89** [comment]
> ```js
> import { randomBytes } from 'react-native-randombytes';
> 
> const getRandom = count => new Promise((resolve, reject) => {
>   return randomBytes(count, (err, bytes) => {
>     if (err) reject(err)
>     else resolve(bytes)
>   })
> })
> ```
> 
> then you can use
> 
> ```js
> async function someFunc() {
>   const entropy = await getRandom(16)
>   console.log(bip39.entropyToMnemonic(entropy))
> }
> ```

You need to do the following for this to work:

yarn add react-native-randombytes
cd ios && pod install 

shim node stream lib like follows:

```

const path = require('path');
module.exports = {
  resolver: {
    extraNodeModules: {
      stream: path.resolve(__dirname, './node_modules/readable-stream'),
    },
  },
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
};



```
