### ISSUE TITLE
String normalization causes issues in spanish wordlist

### ISSUE THREAD

**Issue by Ramarti** [bitcoinjs/bip39#121]
Hi

Just wanted to point out that, when generating a mnemonic, this library does

```
.normalize('NFKD')
```
So mnemonic returned is not rendering correctly when using the spanish wordlist, where we see something like:

![image](https://user-images.githubusercontent.com/2632384/61236141-923caa80-a737-11e9-998a-b21c17ba22a7.png)

which should read `época`

calling .normalize('NFKC') on the output of `generateMnemonic` did fix it, but since it took me a bit of digging to solve it, I think it would be nice to add a mention in to the readme or something like that.

Thanks for the library and your work :)

**Comment by junderw** [comment]
This is part of the BIP39 spec. So it can not be changed...

**Comment by junderw** [comment]
I would also recommend making a bug report with whatever rendering engine you are using.

I don't think that string should render differently based on normalization.
