### ISSUE TITLE
Why is insecure SHA1 in codebase? 

### ISSUE THREAD

**Issue by innerop** [bitcoinjs/bip39#124]
Hi,

I'm a little suspicious whenever I see a crypto codebase that uses a hash function with known flaw, like sha1. I'm not sure if its use in BIP39 affects anything at all but it still raises my suspicion.

While on this topic, has the project received any kind of independent review? 

Kindly,

**Comment by junderw** [comment]
sha1 is not used anywhere. Please show me which line uses SHA1.

> While on this topic, has the project received any kind of independent review?

No. It is open source, and done purely by volunteers. We don't have the money to pay for independent review.

But you can review it if you'd like.

**Comment by junderw** [comment]
I just ran a clean clone on master and fully installed all dependencies.

sha1 hashes are not used anywhere in this library.

**Comment by innerop** [comment]
Hi there,

I just checked, it’s not in your codebase but in one of the dependencies. I was going over the bundle generated by browserify and found sha1 being used for some function as default. When I get home in a few minutes, I’ll send you the line numbers.

**Comment by junderw** [comment]
pbkdf2 uses sha1 as default, But if you look at our library we always pass `'sha512'`

Which makes sense, since SHA1 is not used at all in the BIP39 spec.

**Comment by innerop** [comment]
Yup, I'll have read the spec for BIP39. Thanks..
