### ISSUE TITLE
Not working on IE11

### ISSUE THREAD

**Issue by SDVII** [bitcoinjs/bip39#127]
It's throwing `SCRIPT1002: Syntax error` at:
```js
function bytesToBinary(bytes) {
    return bytes.map(x => lpad(x.toString(2), '0', 8)).join('');
}
```

**Comment by junderw** [comment]
IE11 is not supported without a transpiler.

**Comment by SDVII** [comment]
It's not being transpiled correctly either.
Whenever I transpile it, I get this:
`Uncaught ReferenceError: exports is not defined`
at:
`Object.defineProperty(exports, "__esModule", { value: true });`
