### ISSUE TITLE
Webpack Ignore Plugin not working?

### ISSUE THREAD

**Issue by YanDevDe** [bitcoinjs/bip39#130]
Hello everyone,

I tried the following method:

`new webpack.IgnorePlugin(/^\.\/wordlists\/(?!english)/, /bip39\/src$/)`

But for some reason this is not working and I'm still able to get wordlist from other languages.
I also tried the old method back in times from #118 which is obviously not working too.

Ignoring other package is working fine at my side, as example for "moment"

`new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)`

Was wondering if you could reproduce the issue too?

I'm using Webpack 4.41.5

**Comment by junderw** [comment]
Could you try with an old version of webpack?

Maybe look on their repo to see which version was latests when I merged that PR. Try that version, and if it works, then try asking webpack devs.

**Comment by DougAnderson444** [comment]
According to the [webpack website](https://webpack.js.org/plugins/ignore-plugin/), perhaps it needs to be this instead?

```
new webpack.IgnorePlugin({
        resourceRegExp: /^\.\/(?!english)/, 
        contextRegExp: /bip39\/src\/wordlists$/
    })
```

**Comment by jonathansampson** [comment]
I ran into this today, and was able to exclude non-english list with the following:

```js
plugins: [
    new webpack.IgnorePlugin({
        checkResource (file, path) {
            if (file.includes('/wordlists/') && !file.includes('/wordlists/english')) {
                return true;
            }
            return false;
        }
    })
]
```

I'm certain I could do it with a regular expression as well; I think the main point of confusion for me was the expectation that the `path` would contain the _wordlists_ substring, when in fact it's presented as part of the file/resource value itself.

**Comment by pundoo** [comment]
If you're on Windows, you should use backslash (`\`) for the context :

`new webpack.IgnorePlugin(/^\.\/wordlists\/(?!english)/, /bip39\\src$/)`
                              ^
