### ISSUE TITLE
Why we need a dependency on randombytes package?

### ISSUE THREAD

**Issue by tiero** [bitcoinjs/bip39#133]
Although it's a well-known package, why we need to add an external dependency for just 40line of codes for browsers? (it could be made even less than that) 

```
 crypto.getRandomValues()
```

**Comment by junderw** [comment]
> for browsers

That's the reason. We are using randombytes because we want to support browsers.

If you can make the support smaller and still work securely on most browsers, please create a pull request on the randombytes repo.
