### ISSUE TITLE
Mnemonics generated by Electrum fail validation

### ISSUE THREAD

**Issue by UndefinedBehaviour** [bitcoinjs/bip39#136]
Mnemonics generated by Electrum (tried versions 3.3.8 and 4.0.2) fail validation.
I tried a few e.g.
```
> const mnemonic = 'material young jeans angry consider creek normal before air maze vendor chest'
undefined
> bip39.validateMnemonic(mnemonic)
false
```

Is there an issue?
Or maybe Electrum uses a newer seed generation spec that this library doesn't implement yet?

**Comment by junderw** [comment]
Electrum does not use BIP39

Electrum version >=2: https://github.com/bitcoinjs/electrum-mnemonic
Electrum version <2: https://github.com/you21979/node-electrum-oldmnemonic
