### ISSUE TITLE
Code quality fixes

### ISSUE THREAD

**Issue by joepie91** [bitcoinjs/bip39#138]
Hi,

While reviewing this dependency, I've run across two code quality issues that could have future security implications:

1. Braceless conditionals are used in various places. [This gist](https://gist.github.com/joepie91/203aaa8e36e1eb958fe7) goes into more detail about why this is a security risk.
2. Promisification is done manually with `new Promise`, which is error-prone and tends to invite "callback creep" over time; ie. increasing amounts of non-Promises code stuffed into the `new Promise` callback, which results in unreliable error handling. This should use something like `util.promisify` instead.

To be clear; __neither of these are immediate security issues__, and so there is no time pressure. They are "just" code quality issues that are likely to introduce a bug and/or vulnerability in any future updates :)

**Comment by junderw** [comment]
Thank you for the comments and heart attack inducing title :-)

tweaking the linter settings might catch these problems moving forward.

If you'd like to make a PR with the needed changes I would be open to merging it.

**Comment by joepie91** [comment]
> Thank you for the comments and heart attack inducing title :-)

Hah, sorry! I bolded the "not an immediate issue" thing in the hopes that it wouldn't cause this reaction, but I guess I didn't consider the title :)

> tweaking the linter settings might catch these problems moving forward.

I believe there's an ESLint rule for requiring brackets, but not for the use of `new Promise`. But it's possible that I just missed it.

 > If you'd like to make a PR with the needed changes I would be open to merging it.

I'm about to start my weekend now, but will do so next week. Thanks!

**Comment by lukechilds** [comment]
I agree with enforcing braces.

Re Promise, I think we should also wrap with:

```js
Promise.resolve().then(() => {
});
```

This means we also correctly catch any errors outside `pbkdf2` that `util.promisify` wouldn't catch.

See here for details: https://github.com/bitcoinjs/bitcoinjs-lib/pull/1582#issuecomment-636640255

**Comment by junderw** [comment]
I'm not a fan of promisify... I have some time so I'll make a PR now.

**Comment by junderw** [comment]
I made a PR that hopefully addresses all issues (by limiting the `new Promise` to a small wrapper function that no one should have to touch ever, basically a manual promisify, and then adding the curly rule to TSLINT)
