### ISSUE TITLE
Error: Range consisting of offset and length are out of bounds

### ISSUE THREAD

**Issue by skdev24** [bitcoinjs/bip39#143]
Hey, 

I'm getting this error "Range consisting of offset and length are out of bounds", when calling the method `bip39.mnemonicToSeed`
```
const mnemonic = "butter top unaware common define punch about merge animal sniff give climb";
const password = "";
const seed = await bip39.mnemonicToSeed(mnemonic, password);
```
I tried to debug seems like error is thrown from `pbkdf2` lib, not sure why this is happening.

but If I use 24 words mnemonic it works, then this method gives same error

```
const root = bitcoin.bip32.fromSeed(seed, config.bitcoinNetwork);
```

Version
```
  "bip39": "3.0.2",
```

**Comment by skdev24** [comment]
I went on debugging each line somehow found lib that giving me the error

https://github.com/crypto-browserify/pbkdf2/blob/4a0bc7bc576418f6d0e7f47339b6054f00d07718/lib/sync.js#L37

And this loop is failing because of `createHmac` lib and this is the line which throwing the error

https://github.com/crypto-browserify/createHmac/blob/ebee700081a5ea6d429b4efe60d43ff6a644af78/browser.js#L28

There was a PR related to out of bound bug: https://github.com/crypto-browserify/createHmac/pull/28/commits/4be7e6bf3d964b0f3748eb35056d9485c0003108

But still not sure about the solution here, I'm using this lib for so long never faced this issue.

**Comment by hadus07** [comment]
I'm also having the same problem. `"bip39": "^3.0.2"`

**Comment by skdev24** [comment]
Not sure, but `3.0.2` doesn't have those changes added yet, even If I reference `bip39` to master code still having same issue.

Let me know if you found any solution.

**Comment by hadus07** [comment]
It looks like the root cause is the following: https://github.com/feross/buffer/issues/272

**Comment by skdev24** [comment]
Issue has been fixed update with latest buffer version

```
"buffer": "^6.0.1"
```

[buffer](https://github.com/feross/buffer/issues/272#issuecomment-722001140)
