### ISSUE TITLE
Can I get all the wallet addresses that bitcoinj has generated

### ISSUE THREAD

**Issue by suusofttruongnv** [bitcoinjs/bip39#148]
Can I get all the wallet addresses that bitcoinj has generated

I tried to get the wallet btc using mnemonic in both bitcoinj and bitcoinjs, the two original wallet addresses are the same, but bitcoinj generates multiple wallet addresses, is there any way bitcoinjs can get as many wallet addresses as bitcoinj?

Please help me!!
Sincerely thank you for your help !!

**Comment by junderw** [comment]
Yes you can. Just derive sequential integers for the address index.

**Comment by junderw** [comment]
Please post your JS/TS code if you would like further assistance.

**Comment by suusofttruongnv** [comment]
Here is my code, please show me how to get all wallet addresses like bitcoinj: 

```
const mnemonic = '...';
const seed = bip39.mnemonicToSeedSync(mnemonic);
const node = bip32.fromSeed(seed);
const bitcoinNetwork = bitcoin.networks.testnet
const hdMaster = bitcoin.bip32.fromSeed(seed, bitcoinNetwork)
const address = bitcoin.payments.p2pkh({ pubkey: node.publicKey, bitcoinNetwork }).address;

const keyPair = hdMaster.derivePath('m/0')
const privateKeyBuffer = Buffer.from(keyPair.privateKey);
const privateKey = privateKeyBuffer.toString('hex');

console.log(address + " " + privateKey);
```
Thanks for the help !!

**Comment by suusofttruongnv** [comment]
Here is my code, please show me how to get all wallet addresses like
bitcoinj:

const mnemonic = '...';
const seed = bip39.mnemonicToSeedSync(mnemonic);
const node = bip32.fromSeed(seed);
const bitcoinNetwork = bitcoin.networks.testnet
const hdMaster = bitcoin.bip32.fromSeed(seed, bitcoinNetwork)
const address = bitcoin.payments.p2pkh({ pubkey: node.publicKey,
bitcoinNetwork }).address;

const keyPair = hdMaster.derivePath('m/0')
const privateKeyBuffer = Buffer.from(keyPair.privateKey);
const privateKey = privateKeyBuffer.toString('hex');

console.log(address + " " + privateKey);

Thanks for the help !!

Vào Th 2, 28 thg 12, 2020 vào lúc 12:25 Jonathan Underwood <
notifications@github.com> đã viết:

**Comment by junderw** [comment]
I don't understand.
What is the difference between `node` and `hdMaster`...?
Why is `privateKey` based on `m/0` while `address` is based on `m` paths?

Can you give me a sample mnemonic and the expected addresses + private keys? (multiple)

**Comment by suusofttruongnv** [comment]
You can give me your skype or email, I would like to chat with you. Thanks!!

**Comment by junderw** [comment]
My email is on all my commits, and my github profile.

But tbh, it is better to have these discussions out in the open.
Just make a new mnemonic, put it into your bitcoinj app, and post the addresses and keys that pop out.
If it's a brand new random mnemonic there's no reason why you can't share it openly.

**Comment by suusofttruongnv** [comment]
I am new to bitcoin so do not understand much about it, can you tell me how to get all the wallet address and private key like bitcoinj created?

**Comment by junderw** [comment]
You are saying "like bitcoinj created"

So I am assuming you have an existing app that is using bitcoinj, and you're trying to recreate that in nodejs with bitcoinjs?

In that case, put the following mnemonic into your bitcoinj app and tell me what address(es) it gives you.

`pave cook hair interest sad gift mosquito service early volume deal solar`

**Comment by suusofttruongnv** [comment]
This is my mnemonic :

vicious fork like burden broom couch giraffe foil lobster vehicle over park park

In bitcoinj, the test net, my wallet address is:: 

addr:mkZmHTqtAfqrhrL1kNHPHN7KtyXpLk2AwD  hash160:3760af9bb1a306d8b0d29111a71e1714e848cdf7  (M, root)
      addr:mzfoeKrivn9qwEYY3mXLYeC5t3XMv57e6M  hash160:d216e998c60687222c08a793f838988836a52d8c  (M/0H, account)
      addr:moSQVNyX8axM174vmmUVwsTY8nosUH5eAY  hash160:56e4cb0d4a82541d83b954d68a1bdfb935f9f7d8  (M/0H/0, external)
      addr:mrz6cADNkQKTVR6RednxzXjixpQGtZMDox  hash160:7dcb8da0eeaba02d796a686383c57e1ade6ea617  (M/0H/1, internal)
      addr:mpC8aH8pcrNzy5hzBhTgdgZv12jbs6FBVa  hash160:5f29cf5403cc642728a0c85594aaaeed0323bb5e  (M/0H/0/0)
      addr:mkycrQEFcVKPENg4TPCVyy5aYpYfAyacz6  hash160:3be3a15a2f47daab4b2c450149db30fbe13b89f2  (M/0H/0/1)
      addr:muRTbfmUMt7XSZR143hTWZk6rC7SkvPKwY  hash160:9887ba0980b4a55245f063ac85130122cf882718  (M/0H/0/2)
      addr:mns93KwuVnrnLUrcdeC7o353dQ18hWSXF9  hash160:509a2b8c5277ba49768978a1527aa6954a8cc135  (M/0H/0/3)
      addr:mtoZZtFHEJXVGwwKpm3uCuapaVPioDVrzB  hash160:91bdbc2536395a220a2afa8035fc1a80bc0b801a  (M/0H/0/4)
      addr:muVAUZ1thodKehuFUk9gL1fn6x7QAetihc  hash160:993b18e53391a8b2b803716aaa3028ddef530c71  (M/0H/0/5)
      addr:n364APV7cd7789tuYgXk99d78ZcdGdVuBr  hash160:ec9d443427fc9753b985fd4b3598f2adf690510a  (M/0H/0/6)
      addr:mjHQaE5migddtoynPB5aFhBELWNBWDJDjX  hash160:29509dbb1166c8a5dc80c954c4dc0a6080d40384  (M/0H/0/7)
      addr:mn92ykB6woJsxzXJdRMmrksmaJsZdUk9Ns  hash160:48a3a3bd70e7b5f9774f80624a085179f34f5d02  (M/0H/0/8)
      addr:mwAWVSLMm5gNB8uFwcJMBP99UrZ4FV8pgc  hash160:aba427477bdcfc17cb8f7a8d52aa74aadeadd6cd  (M/0H/0/9)
      addr:mtneUknMcRUjJpZ9UiFMqNs4adM3P7aQ42  hash160:91916b40bf90152aa2b515ffe640c9abcd1412ac  (M/0H/0/10)
      addr:mv6fUfdis6d3BsMvqVBSfALFH4wSBLH8RC  hash160:9ff1dd93926232f3d7141b67a5047afc30496eb6  (M/0H/0/11)
      addr:n3NjerqHtdfJL4Y2x2vb51EwkkGkMS1M1D  hash160:efc4e31bca8baf1032cdcbf30c333e4ccbe28930  (M/0H/0/12)
      addr:mqCjhBLrmrhtSWRz6r7Dpr44q7ehgE2cVP  hash160:6a3f406222e54a43043810cfc9e0e679e4a28acb  (M/0H/0/13)
      addr:mp7zYwwVYZyYZ6JQy2L75e5SzHbxx7Te9h  hash160:5e6172e52a120deca537289323efce05c19f3b5e  (M/0H/0/14)
      addr:mnBfPASXzgV7nFe3FLfGU5op2D276SSEiV  hash160:4922dc202a32037aa3f1722789c9317c66654213  (M/0H/0/15)
      addr:mipfqGKCW3QbYxeFxPAPFVhc4Aip6hTBUr  hash160:24421f7b5e81b9b07289d6c6e2dc2a85c69ab15e  (M/0H/0/16)
      addr:mv4XYD3dCtRe16qzbsYhiUDqGn9Ddmtrk7  hash160:9f8a681189ee7a7e0ba0ea0e82c43c27d064b718  (M/0H/0/17)
      addr:n36hKeLTUAW31mKXSYUM67LatYXXXRkPj8  hash160:ecbc4922740590bb121a4d718d0399831a21aef6  (M/0H/0/18)
      addr:n2ruHmRgd9Tp7FTKCehjtwtAJ9S91uZTd5  hash160:ea2073c915eb88edc96e5bd5c5e44defc9c34487  (M/0H/0/19)
      addr:mzSKqsQNAdGm8TLUMq6uridkzLSFnquTcy  hash160:cf8a4c4384249305afaafd69a83d5c206d63bb47  (M/0H/0/20)
      addr:mik2LFXfKscBy4WrmrZcBZYUCDBJo67MBE  hash160:236127cf8bf28fda358f665073918774ff606648  (M/0H/0/21)
      addr:miwAvQDTxuyx4eHTsSVteQ3ZQDrPuebRs4  hash160:257ce69105b1ba6a0411ab9bbf9957b426167bc5  (M/0H/0/22)
      addr:mydpXc5xqUUhCxBHKEj2TW9aS4wczWDvX7  hash160:c6beb15c8a458da7c703a33d047a92681082a82d  (M/0H/0/23)
      addr:mnQt7mkg8bMzJxufXQEMJ1RsgxYHcLnced  hash160:4ba2e5d0231625db532685de1a4

Thanks for support !!

**Comment by suusofttruongnv** [comment]
Currently I have the private key of one wallet, hopefully from it we will get a way to get the private key of other wallets: 
```
address : mpC8aH8pcrNzy5hzBhTgdgZv12jbs6FBVa
private key : 3d6982c7687c3892ebf32bd092cb2be47d115a39453c218a8e01fd882ec82549
```

**Comment by junderw** [comment]
`getKeysFromMnemonic('vicious fork like burden broom couch giraffe foil lobster vehicle over park park')`

```js
const bip39 = require('bip39')
const bitcoinjs = require('bitcoinjs-lib')

function getKeysFromMnemonic(
  mnemonic,
  keyCount = 25,
  startingKey = 0,
  isChange = false,
  network = bitcoinjs.networks.testnet
) {
  const seed = bip39.mnemonicToSeedSync(mnemonic)
  const root = bitcoinjs.bip32.fromSeed(seed, network)
  const account = root.deriveHardened(0)
  // can also be derived with root.derivePath(`m/0'/0`)
  const external = account.derive(0)
  // can also be derived with root.derivePath(`m/0'/1`)
  const internal = account.derive(1)

  const keys = []
  function pushKey (key, path) {
    const payment = bitcoinjs.payments.p2pkh({
      pubkey: key.publicKey,
      network
    })
    keys.push({
      path,
      address: payment.address,
      hash160: payment.hash.toString('hex'),
      privateKey: key.toWIF(),
    })
  }

  pushKey(root, 'M, root')
  pushKey(account, 'M/0H, account')
  pushKey(external, 'M/0H/0, external')
  pushKey(internal, 'M/0H/1, internal')

  const inExIndex = isChange ? 1 : 0
  const internalOrExternal = isChange ? internal : external
  for (let i = startingKey; i < startingKey + keyCount; i++) {
    const key = internalOrExternal.derive(i)
    pushKey(key, `M/0H/${inExIndex}/${i}`)
  }

  return keys
}
```

```
[
  {
    path: 'M, root',
    address: 'mkZmHTqtAfqrhrL1kNHPHN7KtyXpLk2AwD',
    hash160: '3760af9bb1a306d8b0d29111a71e1714e848cdf7',
    privateKey: 'cMjfaNoB7UFugCpbJjtfyrc5QVEwodAJs8KsinrMVurcJeYZYQXD'
  },
  {
    path: 'M/0H, account',
    address: 'mzfoeKrivn9qwEYY3mXLYeC5t3XMv57e6M',
    hash160: 'd216e998c60687222c08a793f838988836a52d8c',
    privateKey: 'cSndFs3geRvkPpR9xQ7C3JHkxp8crhLmAEcLnjXKry5wq6Z6RqCK'
  },
  {
    path: 'M/0H/0, external',
    address: 'moSQVNyX8axM174vmmUVwsTY8nosUH5eAY',
    hash160: '56e4cb0d4a82541d83b954d68a1bdfb935f9f7d8',
    privateKey: 'cUXnmJ3VjsHRoru5vVeMeJ5jiFDaDrecHXu8f2RLaTKV64vN78Ao'
  },
  {
    path: 'M/0H/1, internal',
    address: 'mrz6cADNkQKTVR6RednxzXjixpQGtZMDox',
    hash160: '7dcb8da0eeaba02d796a686383c57e1ade6ea617',
    privateKey: 'cT9aJHQHKtXjVtRnvcbTDoBs9AQS24vFxoee9JwdKR3Y2qtwVZhP'
  },
  {
    path: 'M/0H/0/0',
    address: 'mpC8aH8pcrNzy5hzBhTgdgZv12jbs6FBVa',
    hash160: '5f29cf5403cc642728a0c85594aaaeed0323bb5e',
    privateKey: 'cPe5XTzR26eJehgRZj42Bfooa2yoLtHUMYbD17C8eJNoRe3y5HXy'
  },
  {
    path: 'M/0H/0/1',
    address: 'mkycrQEFcVKPENg4TPCVyy5aYpYfAyacz6',
    hash160: '3be3a15a2f47daab4b2c450149db30fbe13b89f2',
    privateKey: 'cNyxQnZZ7DXAjrbQgAxMBtp34VR8HaxXGJzTcbVGZU663jMUdtgB'
  },
  {
    path: 'M/0H/0/2',
    address: 'muRTbfmUMt7XSZR143hTWZk6rC7SkvPKwY',
    hash160: '9887ba0980b4a55245f063ac85130122cf882718',
    privateKey: 'cQqMoyktJ6wyhsWwqcioYcyVZ1o2TyKp7E7NmWWSNhXs8bKanioy'
  },
  {
    path: 'M/0H/0/3',
    address: 'mns93KwuVnrnLUrcdeC7o353dQ18hWSXF9',
    hash160: '509a2b8c5277ba49768978a1527aa6954a8cc135',
    privateKey: 'cN8jfW6t9TC4fFkbTcXx59Dp9Rx5hpX6E7pmU9s4zvgNNXnug1QM'
  },
  {
    path: 'M/0H/0/4',
    address: 'mtoZZtFHEJXVGwwKpm3uCuapaVPioDVrzB',
    hash160: '91bdbc2536395a220a2afa8035fc1a80bc0b801a',
    privateKey: 'cRydTi2y86mNsYfxBvk7SNdsAunX5pihAFP4GN5oCQJjnbLH6S85'
  },
  {
    path: 'M/0H/0/5',
    address: 'muVAUZ1thodKehuFUk9gL1fn6x7QAetihc',
    hash160: '993b18e53391a8b2b803716aaa3028ddef530c71',
    privateKey: 'cUtazkrM53EhYWZacAZiyz355crvnxQgnURxhqQ1YuVEyvcNV9BB'
  },
  {
    path: 'M/0H/0/6',
    address: 'n364APV7cd7789tuYgXk99d78ZcdGdVuBr',
    hash160: 'ec9d443427fc9753b985fd4b3598f2adf690510a',
    privateKey: 'cSYMsiEwVVRTmvcQy8Bj9XDXib9gFBsZnWv5w2qCHV7ao22EmxEM'
  },
  {
    path: 'M/0H/0/7',
    address: 'mjHQaE5migddtoynPB5aFhBELWNBWDJDjX',
    hash160: '29509dbb1166c8a5dc80c954c4dc0a6080d40384',
    privateKey: 'cSH3FrQztj4hkpjBXzJixqZY1ktxDUohuQPFckW5avGWiVJdxCHs'
  },
  {
    path: 'M/0H/0/8',
    address: 'mn92ykB6woJsxzXJdRMmrksmaJsZdUk9Ns',
    hash160: '48a3a3bd70e7b5f9774f80624a085179f34f5d02',
    privateKey: 'cMdiutG6R3tVLqTMRHJrCAJSDq7e7H5NuxexYuozw4uVMgAKqxmR'
  },
  {
    path: 'M/0H/0/9',
    address: 'mwAWVSLMm5gNB8uFwcJMBP99UrZ4FV8pgc',
    hash160: 'aba427477bdcfc17cb8f7a8d52aa74aadeadd6cd',
    privateKey: 'cW7QeUVVuETfUqXigndYCprN1vpQAdStbCPaoAT3eEwiNoEviXdp'
  },
  {
    path: 'M/0H/0/10',
    address: 'mtneUknMcRUjJpZ9UiFMqNs4adM3P7aQ42',
    hash160: '91916b40bf90152aa2b515ffe640c9abcd1412ac',
    privateKey: 'cN3BRu9r2Y7rcQf6vtVxDfvq8CejuXpFdqR7SbNd1Tr69yREXdMX'
  },
  {
    path: 'M/0H/0/11',
    address: 'mv6fUfdis6d3BsMvqVBSfALFH4wSBLH8RC',
    hash160: '9ff1dd93926232f3d7141b67a5047afc30496eb6',
    privateKey: 'cSRZVPQd2uzXCTkxVNzVzeQYzZP5tpGoREaFrCfPf2VYpyMWk59c'
  },
  {
    path: 'M/0H/0/12',
    address: 'n3NjerqHtdfJL4Y2x2vb51EwkkGkMS1M1D',
    hash160: 'efc4e31bca8baf1032cdcbf30c333e4ccbe28930',
    privateKey: 'cS9o5rC5e8ft52zXK8zPy9wea6fKTd86b4EPnzKR8o1Xc3yuoHg2'
  },
  {
    path: 'M/0H/0/13',
    address: 'mqCjhBLrmrhtSWRz6r7Dpr44q7ehgE2cVP',
    hash160: '6a3f406222e54a43043810cfc9e0e679e4a28acb',
    privateKey: 'cNge694nzcMujUH4WE1yrb2vqtWzcjqhNkqh6SiKptAVFF64rKfi'
  },
  {
    path: 'M/0H/0/14',
    address: 'mp7zYwwVYZyYZ6JQy2L75e5SzHbxx7Te9h',
    hash160: '5e6172e52a120deca537289323efce05c19f3b5e',
    privateKey: 'cNoyGnqem9RYiEnwUSzcuYKJqiANFbJnfmv3a5Q7A2sm5RnXUyWw'
  },
  {
    path: 'M/0H/0/15',
    address: 'mnBfPASXzgV7nFe3FLfGU5op2D276SSEiV',
    hash160: '4922dc202a32037aa3f1722789c9317c66654213',
    privateKey: 'cTCSmJk8jc2f9BPqstSpWt6QGMmew38Q7dSpGrmaFHQAvaec1MvM'
  },
  {
    path: 'M/0H/0/16',
    address: 'mipfqGKCW3QbYxeFxPAPFVhc4Aip6hTBUr',
    hash160: '24421f7b5e81b9b07289d6c6e2dc2a85c69ab15e',
    privateKey: 'cQDaoZ2RsNpHCpHUDwdXCNjq8sjn5F3fzCXpcomC3f4BYmakcHfq'
  },
  {
    path: 'M/0H/0/17',
    address: 'mv4XYD3dCtRe16qzbsYhiUDqGn9Ddmtrk7',
    hash160: '9f8a681189ee7a7e0ba0ea0e82c43c27d064b718',
    privateKey: 'cUU3SFJxrvFKXzoC1HHusrCNWnce8fqrKBQM4dxGxwJ86Uq2kgBN'
  },
  {
    path: 'M/0H/0/18',
    address: 'n36hKeLTUAW31mKXSYUM67LatYXXXRkPj8',
    hash160: 'ecbc4922740590bb121a4d718d0399831a21aef6',
    privateKey: 'cPfUtdnHCLCP2YhfoKNtsLMKQnYcQEv5CQy8RH96XakPVr59fdyz'
  },
  {
    path: 'M/0H/0/19',
    address: 'n2ruHmRgd9Tp7FTKCehjtwtAJ9S91uZTd5',
    hash160: 'ea2073c915eb88edc96e5bd5c5e44defc9c34487',
    privateKey: 'cTDwNnjnE6mb5fNa8nUeVw4R1evv9zbWmA3RQE95hi9UhGaoCGEv'
  },
  {
    path: 'M/0H/0/20',
    address: 'mzSKqsQNAdGm8TLUMq6uridkzLSFnquTcy',
    hash160: 'cf8a4c4384249305afaafd69a83d5c206d63bb47',
    privateKey: 'cU16NStdhWYnevkUJM9sQdKkj3qAxhwR7dGis2wXi1tTEY4J8VZV'
  },
  {
    path: 'M/0H/0/21',
    address: 'mik2LFXfKscBy4WrmrZcBZYUCDBJo67MBE',
    hash160: '236127cf8bf28fda358f665073918774ff606648',
    privateKey: 'cPn22Ft7dcPFitnuh4Y9zWuhtMm1XyvoV7bdgFW19HDsoV5cB8k8'
  },
  {
    path: 'M/0H/0/22',
    address: 'miwAvQDTxuyx4eHTsSVteQ3ZQDrPuebRs4',
    hash160: '257ce69105b1ba6a0411ab9bbf9957b426167bc5',
    privateKey: 'cPwN8EDPNnR6i8NmuVt2VP5RJdrKLjRHCQfDodeZB7sYPE3DGw7R'
  },
  {
    path: 'M/0H/0/23',
    address: 'mydpXc5xqUUhCxBHKEj2TW9aS4wczWDvX7',
    hash160: 'c6beb15c8a458da7c703a33d047a92681082a82d',
    privateKey: 'cUTYi4PQj8S4Kz59FXYbAhn1n5fJbN2CFrs9is2GqFxp78JUUwcf'
  },
  {
    path: 'M/0H/0/24',
    address: 'mnQt7mkg8bMzJxufXQEMJ1RsgxYHcLnced',
    hash160: '4ba2e5d0231625db532685de1a4789c6c8aab0f9',
    privateKey: 'cQQ625s8k5E4WczbiecMTcBWhReo2fhsKmmUdMMyvkUyaW5p9WVa'
  }
]
```

**Comment by suusofttruongnv** [comment]
Wow !!! Thanks you very much !!!

**Comment by suusofttruongnv** [comment]
How to convert private key : "cPe5XTzR26eJehgRZj42Bfooa2yoLtHUMYbD17C8eJNoRe3y5HXy" -> to private as hex : 
"3d6982c7687c3892ebf32bd092cb2be47d115a39453c218a8e01fd882ec82549" ? 

Thanks you !!

**Comment by junderw** [comment]
`key.toWIF()` -> `key.privateKey.toString('hex')`

**Comment by suusofttruongnv** [comment]
Is the number of wallet addresses created limited? 
Thanks !!

**Comment by junderw** [comment]
minimum index is 0
maximum index is 2147483647 

So you could do
(I updated the function to use an option object instead of a bunch of parameters)
`getKeysFromMnemonic(mnemonic, { startingKey: 2147483647, keyCount: 1 })`
or
`getKeysFromMnemonic(mnemonic, { startingKey: 2147483600, keyCount: 48 })`
if you wanted.

`getKeysFromMnemonic(mnemonic, { keyCount: 2147483647 })`
will take forever.

**Comment by suusofttruongnv** [comment]
Thanks for your answers !!!

**Comment by suusofttruongnv** [comment]
Hello, Is this library for long term use in the future?

**Comment by junderw** [comment]
I don't understand your question.

It is released under the MIT license, so that means:

1. We have no obligation to you. No warranty etc.
2. You have no obligation to us. You can use this forever if you want.

**Comment by suusofttruongnv** [comment]
Thanks you !!!

**Comment by suusofttruongnv** [comment]
Hello bro, I have questions please help me

1. how to send a transaction to an address
2. Show me how to get the transaction history of the wallet

Thank you for your help !!

**Comment by junderw** [comment]
2 is in the integration tests.

1 and 3 are varied and there are many ways to do it. In general you should run your own Bitcoin node and figure out a way to get utxo info from it. (RPC is one way, or some app that sits on top of bitcoin like NBXplorer is another way)

**Comment by suusofttruongnv** [comment]
Hi bro, 
I want to use Bitcoinjs-lib to do the above 3 things, is it possible? if so please let me know the code!
I just want to use Bitcoinjs-lib without a third party!

Thanks !!!
