### ISSUE TITLE
Recovery using only the first four letters of each word

### ISSUE THREAD

**Issue by paulyoung** [bitcoinjs/bip39#158]
Some backup solutions only allow storing the first 4 letters in accordance with the BIP39 protocol.

My understanding is that the first-four-letter combinations are unique and sufficient to recover the full word.

Does this package support that?

It’s something I’m trying to figure out for https://github.com/dfinity/internet-identity/pull/335

**Comment by junderw** [comment]
No. This is easily done with 1 line. Maybe a couple extra lines to check inputs.

```js
function findFirstFour(firstFour, wordlist) {
  if (typeof firstFour !== 'string' || firstFour.length !== 4) throw new Error('Need 4 characters')
  if (!Array.isArray(wordlist) || wordlist.length !== 2048 || wordlist[1353] !== 'powder') throw new Error('Use bip39 English wordlist')

  return wordlist.filter(s => s.startsWith(firstFour))[0]
}
```

**Comment by jcrben** [comment]
I'm using https://github.com/jcrben/ssh-ed25519-bip39 which I tweaked to accept 4 character word abbreviations https://github.com/kolontsov/ssh-ed25519-bip39/compare/master...jcrben:ssh-ed25519-bip39:master

I pushed it up to npm as `jcrben-generate-ssh-from-bip39@0.1.1`
