### ISSUE TITLE
Upgrade deps

### ISSUE THREAD

**Issue by 34r7h** [bitcoinjs/bip39#159]
`npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated eslint-loader@2.2.1: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated sprintf@0.1.5: The sprintf package is deprecated in favor of sprintf-js.
npm WARN deprecated text-encoding@0.7.0: no longer maintained
npm WARN deprecated rollup-plugin-node-resolve@2.1.1: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
npm WARN deprecated rollup-plugin-commonjs@7.1.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-commonjs.`

**Comment by lumsdnb** [comment]
Hey @34r7h,

Try running `npm outdated` to see which ones need an update, then `npm install [package]@latest` for each one. 

Or run `npm update` to do them all at once, could break other things though depending on your project
