### ISSUE TITLE
v3.0.4 is not working, v3.0.3 is fine

### ISSUE THREAD

**Issue by tylim88** [bitcoinjs/bip39#167]
```js
var bip39 = require("bip39");
const mnemonic = bip39.generateMnemonic();
console.log(mnemonic);
```
3.0.4:
![image](https://user-images.githubusercontent.com/5227509/139700374-cc34289d-4f96-4ab3-ad3f-9b9f8597efb9.png)

however 3.0.3 works fine

**Comment by tylim88** [comment]
also, all version 3 is not working in firebase function, version 2.6.0 is working

**Comment by junderw** [comment]
This is an issue with your environment, not the library.

You most likely need to make a shim for randombytes.
