### ISSUE TITLE
Invalid argument(s): Invalid mnemonic

### ISSUE THREAD

**Issue by sayhellotogithub** [bitcoinjs/bip39#168]
bip39: ^1.0.6

#### test code  

test("mnemonic to entropy", () {
    //word nasty space front wealth text hazard nerve dump deer tunnel mirror
    var result= mnemonicToEntropy("word nasty space front wealth text hazard nerve dump deer tunnel mirror");
    print(result);
  });

#### error

package:bip39/src/bip39_base.dart 111:7  mnemonicToEntropy.<fn>
dart:_internal                           ListIterable.join
package:bip39/src/bip39_base.dart 114:6  mnemonicToEntropy
test/mnemonic_test.dart 46:17            main.<fn>

Invalid argument(s): Invalid mnemonic

**Comment by junderw** [comment]
That is not a valid bip39 phrase.

**Comment by sayhellotogithub** [comment]
i know  'dump'

**Comment by sayhellotogithub** [comment]
@junderw  thank you
