### ISSUE TITLE
Using bip39 with React Native

### ISSUE THREAD

**Issue by sunny-g** [bitcoinjs/bip39#29]
I've Browserified the library using `npm run compile` and many other ways, but every time I do I get the same error of `Buffer is not defined` from the `create-hash` module (helpers.js, line 3). Have you gotten this issue before in the browser?

**Comment by sunny-g** [comment]
I also edited the index.js file to before compiling to require `'create-hash/browser'` instead of just `'create-hash'` to no avail.

**Comment by dcousens** [comment]
I haven't had this issue,  are you browserifying in such a way that `Buffer` is ignored?

**Comment by sunny-g** [comment]
I'm browserifying exactly as `npm rum compile` does it as well as trying `browserify index.js -o bip39.js` so that it can be `require`d appropriately. 

One fix I found was to add this line before requiring bip39, but then I get an `assert is not defined` error:
```
global.Buffer = global.Buffer || require('buffer').Buffer;
```
which suggests to me that I'm going have to do this for every Node.js module I want to use. I'm currently looking for a more reasonable alternative to this.

**Comment by dcousens** [comment]
Check the resultant file, if `"Buffer"` doesn't exist, something is terribly wrong.
What browserify/node/npm version?

**Comment by sunny-g** [comment]
node: 0.12.7
npm: 2.11.3
browserify: 12.0.1

If you run `browserify index.js -o bip39.js` with these settings, at line 365 begins the IIFE defining the `Buffer` class. `assert`'s definition is the first thing code after the big one-liner from browserify.

**Comment by dcousens** [comment]
How are you then using `bip39.js`?

**Comment by sunny-g** [comment]
So as it turns out there are three ways I can use it (the `npm run compile`d version only), of which only the last method works:

1. bip39.js in the same folder as index.js, and the code I use is`let bip39 = require('bip39/bip39');` - get the `Buffer is not defined` error.

2. bip39.js in the same folder as index.js, and the code is `let bip39 = require('../../node_modules/bip39/bip39.js');`- same `Buffer is not defined` error.

3. bip39.js inside my `src/`, and the code is `let bip39 = require('./bip39.js');` - and this works!

I'm almost certain this has something to do with React Packager and not your library, so I really appreciate your help!

**Comment by dcousens** [comment]
```
require('bip39') is all you should need
```

If that doesn't work, then something is wrong with you are using react native.

**Comment by dcousens** [comment]
@sunny-g I assume this all worked out in the end?
