### ISSUE TITLE
Entropy?

### ISSUE THREAD

**Issue by chris41188** [bitcoinjs/bip39#31]
Hi
In this line

var mnemonic = bip39.entropyToMnemonic('133755ff') // hex input, defaults to BIP39 English word list

what is the 133755ff? is this a random string we enter inorder to create entropy? more entropy?

**Comment by jprichardson** [comment]
Hi @chris41188,

Hopefully this clears it up:

```js
var crypto = require('crypto')
var bip39 = require('bip39')

var entropy = crypto.randomBytes(16)
var mnemonic = bip39.entropyToMnemonic(entropy.toString('hex'))
console.log(mnemonic)
```

> what is the 133755ff? is this a random string we enter inorder to create entropy?

Strictly speaking, you'd use `crypto.randomBytes` to generate entropy. However, you can combine it with other techniques to get even more entropy.

**Comment by chris41188** [comment]
Hi JP

Thank you for your reply, that makes sense.
I was told that crypto.randomBytes is not secure because it partially uses a timestamp to create randomness and if a hacker knew this time stamp or roughly the time the mnemonic was made then it gives them an attack vector for a brute force attack.

from crypto.js
// Mix in the current time (w/milliseconds) into the pool
    var rng_seed_time= function () {
    	rng_seed_int( new Date().getTime() );
    };
    

is this true? 
Also how much entropy is needed here? 

thanks

**Comment by jprichardson** [comment]
`crypto.randomBytes` is cryptographically secure. Here, some cozy reading for you:

- http://crypto.stackexchange.com/questions/12436/what-is-the-difference-between-csprng-and-prng
- http://stackoverflow.com/questions/2449594/how-does-a-cryptographically-secure-random-number-generator-work
- https://github.com/nodejs/node/blob/b4d4fd939c813177209fc6a2f32a3a125122de7c/test/addons/openssl-binding/binding.cc#L20
- https://www.openssl.org/docs/manmaster/crypto/RAND_bytes.html
- https://github.com/nodejs/node/tree/master/deps/openssl/openssl

**Comment by chris41188** [comment]
Thanks you I may have been confused, I was using this an altered version of
securerandom.js that took out csprng because it wasnt run in the browser
(it was run in titanium sdk)
