### ISSUE TITLE
Please add "standard" word list in other languages

### ISSUE THREAD

**Issue by Polve** [bitcoinjs/bip39#39]
Hello,
while programming it's nice to have the wordlist you provide in this package, and more so it would be useful if you could do a newer release with other bip39 accepted wordlist as available here:

https://github.com/bitcoin/bips/tree/master/bip-0039

In particular for Italian, French and Spanish.

**Comment by dcousens** [comment]
Closing in favour of #40

**Comment by fanatid** [comment]
@Polve 2.3.0 was released with french, italian and spanish
