### ISSUE TITLE
Please add chinese simplified and traditional dictionary files

### ISSUE THREAD

**Issue by jcalfee** [bitcoinjs/bip39#50]
https://github.com/bitcoin/bips/tree/master/bip-0039

**Comment by fanatid** [comment]
fix `WORDLIST` in https://github.com/bitcoinjs/bip39/blob/master/util/wordlists.js
and run script

**Comment by dcousens** [comment]
@jcalfee PR's accepted :+1:

**Comment by dcousens** [comment]
Added in https://github.com/bitcoinjs/bip39/pull/55
