### ISSUE TITLE
var mnemonic = bip39.generateMnemonic(256)

### ISSUE THREAD

**Issue by jadster** [bitcoinjs/bip39#59]
How can I call `generateMnemonic` with non-english wordlist? I can't get it to work.

choosing "strength" works fine: `bip39.generateMnemonic(256) `.
But I can't seem to choose a specific wordlist, e.g. french.

Help appreciated.

**Comment by dcousens** [comment]
> function generateMnemonic (strength, rng, wordlist)

Therefore

``` js
var mnemonic = bip39.generateMnemonic(256, null, bip39.wordlists.french)
```

**Comment by jadster** [comment]
Thank you!
