### ISSUE TITLE
Error: Private key must be less than the curve order

### ISSUE THREAD

**Issue by m-king** [bitcoinjs/bip39#60]
I'm attempting to use the library with MeteorJs instead of browserify. Everything works fine on the server side, on the client I'm running into an Exception with message 

> Error: Private key must be less than the curve order

On the client the following works fine
`var key = bitcoin.ECPair.makeRandom();`
`console.log(key.getAddress());`

But if I want to generate keys through mnuemonic phrases instead I get the above exception. See code below.

`this.mnemonic = bip39.generateMnemonic();`
`let mnemonicSeedHex = bip39.mnemonicToSeedHex(this.mnemonic);`
`let node = bitcoin.HDNode.fromSeedHex(mnemonicSeedHex, bitcoin.networks.testnet);`
`console.log(node.getAddress());`

I assume its something down to Buffer in the browser?

**Comment by dcousens** [comment]
> I assume its something down to Buffer in the browser?

Potentially.
Can you `console.log(mnemonicSeedHex)` and show it here?

**Comment by m-king** [comment]
Sure

230328f130f9315df443b162ddf93748fad39cdc30f0dfc2a1f64db18f14e4e2e923b6242fff08b91d830924b8c4ae9f79a9d1b6ba9911726ff95b01103355ea

**Comment by dcousens** [comment]
Using

``` js
let bitcoin = require('bitcoinjs-lib')
let bip39 = require('bip39')

let mnemonic = 'message foot patrol now film mansion spy wide bean latin unhappy toe'
let seedHex = bip39.mnemonicToSeedHex(mnemonic)
let node = bitcoin.HDNode.fromSeedHex(seedHex)

console.log({
  mnemonic,
  seed: seedHex,
  node: node.toBase58()
})
```

``` json
{
  mnemonic: "message foot patrol now film mansion spy wide bean latin unhappy toe",
  seed: "364a3f598f18728aad44ddcac53b45cfd510cb67679e940366c0500b026de2d642acaaa8ee7777d76b0a1e40c730294f0bf6a649cd6791b13446adaf41ea9da1",
  node: "xprv9s21ZrQH143K2SMXRvyZbVP6dEkPHmRb6cf7yDaco8v8eoKhXHqNy9SBtzTsg9QvEHedh6HU4Khxwb22dYiiS69W8Ny9X33PX5UMEhCR44o"
}
```

Could not reproduce `Error: Private key must be less than the curve order`.

Could you try and print out what the private key is before it reaches `Error: Private key must be less than the curve order`?
This definitely looks to be a meteorjs issue.

**Comment by m-king** [comment]
Right think its something to do with the Uint8Array.slice() in HDNode.fromSeedBuffer

I don't know why but they're both returning full arrays of 64 elements instead of the 32. Thought it might be a bug in FF but its happening in chrome too. I guess the issue must be Meteor messing with typedarray methods or similar? Any thoughts? I'll dig into Meteor now see if I can see anything

`var IL = I.slice(0, 32)`
`var IR = I.slice(32)`

**Comment by m-king** [comment]
If anyone encounters this problem, in my case it was down to using an older version of the npm Buffer library (< 4).

`npm install buffer` fixed the issue be updating the library. Thanks for the help @dcousens closing ticket.
