### ISSUE TITLE
Wrong master key derived.

### ISSUE THREAD

**Issue by mmick66** [bitcoinjs/bip39#64]
I am trying to use this library to generate keys. I have:

```
let seed        = bip39.mnemonicToSeed(mnemonic);
let master      = bitcoin.HDNode.fromSeedBuffer(seed, bitcoin.networks['testnet']);
let derived     = master.deriveHardened(0).toBase58();
```

But the result is not consistent with: http://bip32.org/

**Comment by dcousens** [comment]
@mmick66 what result is not consistent?
The

**Comment by mmick66** [comment]
Thank you for clarifying. My mistake for not investigating further.
