### ISSUE TITLE
How to translate keystore / private key to mnemonic?

### ISSUE THREAD

**Issue by mobilesite** [bitcoinjs/bip39#69]
Excuse me! Is there any method to translate keystore / private key to mnemonic, or is it possible? Thank you!

**Comment by dcousens** [comment]
What do you mean by `keystore`?

**Comment by mobilesite** [comment]
@dcousens I mean keystore file of an ethereum wallet.

**Comment by dcousens** [comment]
No idea about that.  But,  `entropyToMnemonic` is probably closest to what you need.

**Comment by fanatid** [comment]
For extracting private key from keystore you can use https://github.com/ethereumjs/keythereum
