### ISSUE TITLE
TypeError: Invalid entropy

### ISSUE THREAD

**Issue by flute** [bitcoinjs/bip39#73]
I'm try to get mnemonic with privateKey, get error: `TypeError: Invalid entropy`

privateKey like this: `0xbe03b2771ad49bac7dda1980687fdb1b5b4fce6a5ec7597923c3e3460687a576`

my code like this: 
```js
const bip39 = require('bip39')
let mnemonic = bip39.entropyToMnemonic(String(privateKey))
```

is there any mistake i make?

**Comment by dcousens** [comment]
`0x`
