### ISSUE TITLE
How can I generate a mnemonic from a private key?

### ISSUE THREAD

**Issue by NullVoxPopuli** [bitcoinjs/bip39#79]
lets say I already have a 128bit Uint8Array,  representing a private key.

How would I generate a mnemonic from that?

**Comment by dcousens** [comment]
A private key is 256 bit...

**Comment by NullVoxPopuli** [comment]
ok, lets say I have a 256bit Uint8Array? :-)

**Comment by dcousens** [comment]
`entropyToMnemonic` will likely be what you want.

**Comment by NullVoxPopuli** [comment]
entropy isn't a private key though.

I ended up implementing my own: https://github.com/NullVoxPopuli/emberclear/blob/master/src/utils/mnemonic/utils.ts#L21
tests: https://github.com/NullVoxPopuli/emberclear/blob/master/src/utils/mnemonic/unit-test.ts
:)

**Comment by dcousens** [comment]
``` js
let bip39 = require('../')
let ent = Buffer.from([43, 191, 106, 38, 141, 42, 151, 128, 227, 93, 124, 214, 166, 222, 144, 176, 162, 181, 203, 27, 39, 18, 37, 173, 2, 189, 139, 8, 181, 8, 171, 45]) // from your `unit-test.ts` file
let mnemonic = bip39.entropyToMnemonic(ent)

console.log(ent.toString('hex'))
// 2bbf6a268d2a9780e35d7cd6a6de90b0a2b5cb1b271225ad02bd8b08b508ab2d

console.log(mnemonic)
// close win meadow bottom practice scatter miracle question stove dad picnic genuine clip tortoise hold time certain gym quarter bid mercy lounge protect remove

console.log(bip39.mnemonicToEntropy(mnemonic).toString('hex'))
// 2bbf6a268d2a9780e35d7cd6a6de90b0a2b5cb1b271225ad02bd8b08b508ab2d
```

If that isn't exactly what you wanted,  I don't know what is.  It seems you've simply re-implemented a BIP39-like transform in your code.

**Comment by NullVoxPopuli** [comment]
Hmm, seems i just misunderstood what was intended by 'entropy'. 

I didn't think it'd be equivalent to a 256 bit private key.

Also, interesting how our mnemonics arre different. I wonder if i did the endianness wrong. Hmm
