### ISSUE TITLE
TypeError:Password must be a buffer of string

### ISSUE THREAD

**Issue by ezailWang** [bitcoinjs/bip39#80]
` const mnemonic = bip39.generateMnemonic();
    const seed = bip39.mnemonicToSeedHex(mnemonic);`
When I run this code, I always have the above error

**Comment by fanatid** [comment]
Because second argument (password) should be passed: https://github.com/bitcoinjs/bip39/blob/v2.5.0/index.js#L50-L59

@dcousens @junderw should we set `password` as zero buffer by default?

**Comment by dcousens** [comment]
@fanatid we didn't default it to enforce that developers know that a password can be provided.  Many BIP39 compliant wallets don't support user-provided passwords,  which is frustrating.

**Comment by ezailWang** [comment]
But the"Password" of error doesn't mean the second argument here.
`pbkdf2(mnemonicBuffer, saltBuffer, 2048, 64, 'sha512')

function pbkdf2 (password, salt, iterations, keylen, digest) {
  checkParameters(password, salt, iterations, keylen)
...
}
`

The first argument here is the wrong one. If I change the check order, the second argument will also go wrong.

`function checkBuffer (buf, name) {
  if (typeof buf !== 'string' && !Buffer.isBuffer(buf)) {
    throw new TypeError(name + ' must be a buffer or string')
  }
}

module.exports = function (password, salt, iterations, keylen) {
  checkBuffer(password, 'Password')
  checkBuffer(salt, 'Salt')

  if (typeof iterations !== 'number') {
    throw new TypeError('Iterations not a number')
  }

  if (iterations < 0) {
    throw new TypeError('Bad iterations')
  }

  if (typeof keylen !== 'number') {
    throw new TypeError('Key length not a number')
  }

  if (keylen < 0 || keylen > MAX_ALLOC || keylen !== keylen) { /* eslint no-self-compare: 0 */
    throw new TypeError('Bad key length')
  }
}
`

**Comment by dcousens** [comment]
That,  is odd.

https://github.com/bitcoinjs/bip39/blob/bafbcd352a6a5275bbc640a79c3917d0baee5bc8/index.js#L51 should enforce that the `password` argument to PBKDF2 is a `Buffer`...

**Comment by junderw** [comment]
works for me...

unless you give us the actual inputs that caused your problem OR the actual code that caused your problem, we can't really help much.

**Comment by junderw** [comment]
Also, @dcousens unorm when called with undefined returns empty string `''`

```bash
> unorm.nfkd(undefined)
''
```

**Comment by ezailWang** [comment]
My running environment is react-native, and I found that `buffer` was imported into the `bip39`.
`var Buffer = require('safe-buffer').Buffer`
Unlike the buffer used in `precondition.js`, `buffer` is not referenced in `precondition.js`.

<img width="286" alt="2018-05-18 2 33 34" src="https://user-images.githubusercontent.com/38491708/40219928-0e2239ac-5aaa-11e8-9820-6ff792131f4a.png">

**Comment by junderw** [comment]
```javascript
> var pbkdf2 = require('pbkdf2').pbkdf2Sync
> pbkdf2(undefined, undefined, 2048, 64, 'sha512')
TypeError: Password must be a buffer or string
    at checkBuffer (/home/jonathan/node_modules/pbkdf2/lib/precondition.js:5:11)
    at module.exports (/home/jonathan/node_modules/pbkdf2/lib/precondition.js:10:3)
    at nativePBKDF2Sync (/home/jonathan/node_modules/pbkdf2/index.js:17:3)
```

looks like the reason is because `Buffer.from` is returning undefined.

This is a react-native problem. Please ask them how to fix `safe-buffer` package for react-native.

**Comment by ezailWang** [comment]
Find a solution and add this code before referring to bip39.
`global.Buffer = require('safe-buffer').Buffer;`

**Comment by dcousens** [comment]
@ezailWang go complain to Facebook that they are doing a terrible job at supporting `Buffer`.

**Comment by ezailWang** [comment]
I feel like I've been complaining enough to them that I'm not friendly to the new guy.
