### ISSUE TITLE
Error if module imported

### ISSUE THREAD

**Issue by gagantaneja** [bitcoinjs/bip39#84]
`import bip39 from 'react-native-bip39';

var mnemonic = bip39.generateMnemonic();`

I get an error "Unable to resolve module 'assert' from '----/node_modules/react-native-bip39/index.js':
Module 'assert' does not exist in the Haste module map .

Anyone please help me out!

**Comment by fanatid** [comment]
This is not `react-native-bip39`, you should open issue in correct repo.
