### ISSUE TITLE
Not working in React-Native

### ISSUE THREAD

**Issue by gagantaneja** [bitcoinjs/bip39#85]
I tried to install bip39 to my react-native app, but when I try to generateMnemonic. I get this error.
![simulator screen shot - iphone 6 - 2018-07-10 at 16 13 47](https://user-images.githubusercontent.com/34162749/42505542-a5875170-845c-11e8-921f-21515f586862.png)

Here is what I did : 
1. npm install bip39
2. Code: `import bip39 from 'bip39';
generateMnemonic() {
		const mnemonic = bip39.generateMnemonic();
		console.log(mnemonic);
	}`.

Please help me out on this

**Comment by setok16** [comment]
I think that you'd need to install the stream module as it seems like a dependency for bip39.

I've run into a different error after installing the stream package.
![simulator screen shot - iphone 8 plus - 2018-07-20 at 12 48 52](https://user-images.githubusercontent.com/25028022/42983292-db4d482a-8c20-11e8-8f90-e3cee215fda8.png)
I found a stackoverflow thread [here](https://stackoverflow.com/questions/51241650/how-can-i-use-socket-io-stream-on-react-native), but it doesn't seem to be resolved.

**Comment by devsarosh** [comment]
try installing rn-nodeify --- https://www.npmjs.com/package/rn-nodeify

**Comment by RajanJS** [comment]
+1
