### ISSUE TITLE
no word "futal" in english wordlist

### ISSUE THREAD

**Issue by jmike1211** [bitcoinjs/bip39#92]
i use bitcoinjs\bip39 ,generate the word "futal" but not in your wordlist

**Comment by fanatid** [comment]
which version you use?

**Comment by fanatid** [comment]
There is such word in published package, can you show you code?
```
curl -s --output - https://registry.npmjs.org/bip39/-/bip39-2.5.0.tgz | tar -xzO package/wordlists/english.json | grep 'futal'
```

**Comment by jmike1211** [comment]
i solves it, maybe i key wrong word,thanks a lot
