### ISSUE TITLE
[proposal] Add Installation to the README.md

### ISSUE THREAD

**Issue by GustavoRSSilva** [bitcoinjs/bip39#93]
I am creating a btc wallet in javascript  with this this library to generate the seed. 

In order to get a little more safe, and to avoid the typing soemthing like
 ``` npm install bip-39 ```
add the command to add the bip 39 to the README.md.

Just as bitcoinlib-js:

![screenshot from 2018-10-31 16-06-05](https://user-images.githubusercontent.com/8384988/47802751-e2e6b180-dd28-11e8-928f-6043501d63a3.png)

(I didn't do the PR myself to not come as imposing, if everyone agrees, I will gladly do it).

**Comment by sesam** [comment]
Seems like a good idea. With no opposition, maybe just go for the PR. cc @dcousens @junderw

**Comment by junderw** [comment]
I wouldn't be opposed to the idea. You can go ahead and make a PR and I'll merge it.

**Comment by GustavoRSSilva** [comment]
@junderw we can close this Issue.
