### ISSUE TITLE
Performance of bip39.mnemonicToSeed

### ISSUE THREAD

**Issue by mesqueeb** [bitcoinjs/bip39#99]
In my JavaScript app (browser) `bip39.mnemonicToSeed(seedPhrase)` takes about 1500ms.

Is there anyway to improve the speed of this function?

**Comment by junderw** [comment]
mnemonicToSeed has like 3 lines of string concatenation and then uses pbkdf2Sync with 2048 iterations of sha-512...

The only way I could see a performance improvement in the browser is maybe by using WebAssembly.

(I wonder if there is a pbkdf2 wasm library out somewhere yet...)

**Comment by mesqueeb** [comment]
Currently the thread gets completely locked for about 1500 ms.
Is there any way split the work between multiple event loop cycles?
Or have an effect that's similar to "time slicing" as explained by Evan You of VueJS here in this presentation: https://youtu.be/8Hgt9HYaCDA?t=1995

**Comment by junderw** [comment]
That would be a question for pbkdf2 https://github.com/crypto-browserify/pbkdf2

**Comment by mesqueeb** [comment]
@junderw I read a bit in the source code and now I understand what you mean! ☺️
any chance you can take a look at this alternative?
https://github.com/asmcrypto/asmcrypto.js

Though I'm not sure if it'll do what you'd need, as I'm not an expert on the topic. 😭

**Comment by calvinmetcalf** [comment]
the async version of pbkdf2 uses the in browser crypto object which is non blocking

**Comment by calvinmetcalf** [comment]
to clarify change [this line](https://github.com/bitcoinjs/bip39/blob/250e3e3a075736d4a2f15f6980e0a2947821346b/index.js#L3) to `var pbkdf2 = require('pbkdf2').pbkdf2` and then pass a callback on [this line](https://github.com/bitcoinjs/bip39/blob/250e3e3a075736d4a2f15f6980e0a2947821346b/index.js#L54) you will have to change your function signatures to accept callbacks or promises but you'd have to do that with any of your ideas you had.

for reference the library you are using is just a pure js version of the [node.js standard library](https://nodejs.org/api/crypto.html#crypto_crypto_pbkdf2_password_salt_iterations_keylen_digest_callback) so the api is (ideally) identical.

**Comment by mesqueeb** [comment]
@junderw Could you work with this suggestion from Calvin?
If you are quite busy I could try and make a PR?

Best regards.

**Comment by junderw** [comment]
perhaps adding an async function would be fine.

If anyone wants to take a crack I can review and merge. Return a promise is probably best.

leave the sync method as is to keep backwards compat.

I'll get to it on Monday if no PR.

**Comment by junderw** [comment]
Could someone test it out / benchmark it?

I have a branch here, but would like OP to use it and see if it actually fixes anything.

The two new methods take the same args and return a promise of the data.

https://github.com/bitcoinjs/bip39/tree/addAsync

**Comment by junderw** [comment]
I am running some benchmarks and they don't look that much different performance-wise...
The only difference is one frees up the EventLoop.

However, I am not sure how to simulate your environment and not sure exactly what you're looking for when you say "Performance"

I would assume this uses some sort of background worker on the browser implementation, which means the JS engine would be freed up to draw the screen and won't freeze up.

Anywho, I am awaiting your response on whether using this method helps you, and if you could explain how it would help. Thanks.

**Comment by mesqueeb** [comment]
@junderw ok please hold on!

**Comment by junderw** [comment]
mnemonicToSeedAsync and mnemonicToSeedHexAsync

Just add Async at the end of the function and it will return a promise

**Comment by junderw** [comment]
For NodeJS (not the browser) this is what I found:

1. await on each loop = time required is almost same as Sync, a tad longer even. only one core is used by node process.
2. push the promises onto an Array, then await Promise.all(array) at the end of the loop = async is 2x faster, all 4 cores are used by the node process.

So it does seem like it's faster, but mostly because the implementation takes advantage of multiple cores when using the async method.

I would assume something similar in the browser.

**Comment by mesqueeb** [comment]
@junderw I just finished testing.
WOW! For me it's **a lot faster!!!!**

Thank you so much!!

I'm building a browser application and this is the code:
```js
  let t0, t1
  t0 = performance.now()
  const seedOLD = bip39.mnemonicToSeed(seedPhrase) // takes 1000~1500ms
  t1 = performance.now()
  console.log(`create seedOLD took ${(t1 - t0)} ms!`)
  t0 = performance.now()
  const seed = await bip39.mnemonicToSeedAsync(seedPhrase) // takes <10ms
  t1 = performance.now()
  console.log(`create seed took ${(t1 - t0)} ms!`)
```
This shows this in the console log:
> create seedOLD took 1283.4949999814853 ms!
> create seed took 8.230000006733462 ms!

Also, the first approach completely blocks the UI so the browser window cannot be scrolled or interacted with.
The second one doesn't. But since it only takes 10 ms, it's even better!!


Thank you so much for this push! I can't wait until it goes to master branch and gets pushed to NPM!!! ❤️❤️❤️❤️

**Comment by junderw** [comment]
ok, I'll go ahead and make a PR.

**Comment by mesqueeb** [comment]
Any updates on this? I can't wait!! 🌝

**Comment by junderw** [comment]
I was able to merge the new async functionality to master, but I don't have publish rights to npm, and currently bumping version tags and the like are locked down, so my hands are tied.

@mesqueeb Could you make a new pull request that merges `bump260` branch into `master` branch?

![スクリーンショット_2019-03-20_16-04-02](https://user-images.githubusercontent.com/11246316/54665252-df15c900-4b29-11e9-9baf-26e0a001c6cd.png)
